### ISSUE TITLE
Default branch develop ?

### ISSUE THREAD

**Issue by actonDev** [diadochos/org-babel-eval-in-repl#27]
Hey @diadochos a small nitpick. I noticed the default github branch is `develop`, which doesn't make a lot of sense (though the melpa recipe correctly points to `master`)

**Comment by diadochos** [comment]
Hi @actonDev! Thanks for your input. I think you're right.
(Historically, my initial intention was to use `master` as the publishing branch and `develop` as the main repository, but that's not standard practice today.)

I'll change the setting so that `master` becomes the default branch. Thanks!

**Comment by diadochos** [comment]
Done!
