### ISSUE TITLE
Add a GIF demo to README

### ISSUE THREAD

**Issue by diadochos** [diadochos/org-babel-eval-in-repl#28]
@actonDev kindly suggested adding a gif to README. I think it's a great idea!

**Comment by diadochos** [comment]
https://github.com/diadochos/org-babel-eval-in-repl/issues/15#issuecomment-552185140

**Comment by diadochos** [comment]
https://github.com/diadochos/org-babel-eval-in-repl/issues/15#issuecomment-552865320

**Comment by actonDev** [comment]
Sure (replying to the linked comment), so just add the gif in the readme, no?

**Comment by actonDev** [comment]
hey @diadochos , how about closing this issue? :)

**Comment by diadochos** [comment]
Hi @actonDev , thanks! Let's do so.
